# Generated by Django 5.0.6 on 2024-07-03 00:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndlite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('pronouns', models.CharField(choices=[('HH', 'He/Him'), ('SS', 'She/Her'), ('TT', 'They/Them'), ('HT', 'He/They'), ('ST', 'She/They'), ('IR', 'I rather not to say'), ('OT', 'Other')], default='IR', max_length=2, verbose_name='Pronouns')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
