# Generated by Django 5.0.6 on 2024-07-03 03:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndlite', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name="User's profile"),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name="Campaign's name")),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('DM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DM', to=settings.AUTH_USER_MODEL, verbose_name='Dungeon Master')),
                ('players', models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='Players')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaignMaps', verbose_name='File')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='dndlite.campaign', verbose_name="Campaign's map")),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaignPictures', verbose_name='File')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='dndlite.campaign', verbose_name="Campaign's picture")),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name="Character's name")),
                ('race', models.CharField(max_length=30, verbose_name="Character's race")),
                ('class_name', models.CharField(max_length=30, verbose_name="Character's class")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='dndlite.campaign', verbose_name='Campaign')),
                ('character', models.ManyToManyField(related_name='log', to='dndlite.character', verbose_name='Character')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='characters', to='dndlite.character', verbose_name='Characters'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('action_type', models.CharField(max_length=30, verbose_name='Type')),
                ('target', models.CharField(blank=True, max_length=70, verbose_name='Target')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dndlite.campaign', verbose_name='Campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='dndlite.character', verbose_name='Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Strength')),
                ('DEX', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Dexterity')),
                ('CON', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Constitution')),
                ('INT', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Intelligence')),
                ('WIS', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Wisdom')),
                ('CHA', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Charisma')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='dndlite.character', verbose_name='Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Level')),
                ('background', models.TextField(blank=True, max_length=20, verbose_name='Background')),
                ('alignment', models.CharField(max_length=30, verbose_name='Alignment')),
                ('personality_traits', models.TextField(blank=True, max_length=100, verbose_name='Personality traits')),
                ('ideals', models.TextField(blank=True, max_length=100, verbose_name='Ideals')),
                ('bonds', models.TextField(blank=True, max_length=250, verbose_name='Bonds')),
                ('flaws', models.TextField(blank=True, max_length=100, verbose_name='Flaws')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='About')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='dndlite.character', verbose_name='Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='characterPictures', verbose_name='File')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='dndlite.character', verbose_name="Character's Picture")),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HP', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(560)], verbose_name='Hit Points')),
                ('XP', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(355000)], verbose_name='Experience Points')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='dndlite.character', verbose_name='Stats')),
            ],
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feets', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(253440)], verbose_name='Feets')),
                ('y_position', models.IntegerField(default=0, verbose_name='Y Position')),
                ('x_position', models.IntegerField(default=0, verbose_name='X Position')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dndlite.campaign', verbose_name='Campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='dndlite.character', verbose_name='Character')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profilePictures', verbose_name='File')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='dndlite.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('reaction_type', models.CharField(max_length=30, verbose_name='Type')),
                ('target', models.CharField(blank=True, max_length=70, verbose_name='Target')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='dndlite.campaign', verbose_name='Campaign')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='dndlite.character', verbose_name='Character')),
            ],
        ),
    ]
