# Generated by Django 5.0.6 on 2024-07-05 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndlite', '0003_alter_profile_user_campaign_campaignmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(blank=True, upload_to='profilePictures', verbose_name='File'),
        ),
    ]
